### ISSUE TITLE
violates FK constraints deleting posts with reply context

### ISSUE THREAD

**Issue by karadaisy** [kylewm/woodwind#13]
```
[2015-02-26 16:58:27,390: ERROR/MainProcess] Task woodwind.tasks.update_feed[3aa718d3-5bcd-4235-ba1f-5d1be4a438bd] raised unexpected: InvalidRequestError('This Session\'s transaction has been ro
lled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (IntegrityError) update or delete on tab
le "entry" violates foreign key constraint "entry_to_reply_context_context_id_fkey" on table "entry_to_reply_context"\nDETAIL:  Key (id)=(19311) is still referenced from table "entry_to_reply_co
ntext".\n \'DELETE FROM entry WHERE entry.id = %(id)s\' {\'id\': 19311}',)
Traceback (most recent call last):
  File "/srv/www/kylewm.com/woodwind/venv/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/www/kylewm.com/woodwind/venv/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/www/kylewm.com/woodwind/woodwind/tasks.py", line 67, in update_feed
    process_feed(session, feed)
  File "/srv/www/kylewm.com/woodwind/woodwind/tasks.py", line 117, in process_feed
    session.commit()
  File "/srv/www/kylewm.com/woodwind/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/srv/www/kylewm.com/woodwind/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 375, in commit
    self._assert_active(prepared_ok=True)
  File "/srv/www/kylewm.com/woodwind/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.ro
llback(). Original exception was: (IntegrityError) update or delete on table "entry" violates foreign key constraint "entry_to_reply_context_context_id_fkey" on table "entry_to_reply_context"
DETAIL:  Key (id)=(19311) is still referenced from table "entry_to_reply_context".
```

**Comment by karadaisy** [comment]
let's try just not deleting previous versions, and clean up manually later if necessary ht @dissolve
