### ISSUE TITLE
SQLite not supported anymore

### ISSUE THREAD

**Issue by jeena** [kylewm/woodwind#53]
Somehow I think there is something missing in the requirements.txt because I get this error when I try to initialize the db:

```
➜ jeena@Lala woodwind (master) python init_db.py
Traceback (most recent call last):
  File "init_db.py", line 3, in <module>
    from woodwind import create_app
  File "/Users/jeena/Projects/woodwind/woodwind/__init__.py", line 1, in <module>
    from .app import create_app
  File "/Users/jeena/Projects/woodwind/woodwind/app.py", line 1, in <module>
    from woodwind import extensions
  File "/Users/jeena/Projects/woodwind/woodwind/extensions.py", line 1, in <module>
    from flask.ext.login import LoginManager
ImportError: No module named flask.ext.login
```

Any tips on how to get this working?

**Comment by jeena** [comment]
Apparently I didn't install all of the requirenments because it crashed before it was done. I found out that I have to source the environment first before I run the installation by doing this: `source venv/bin/activate` 

Now I am getting a different error:

```
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0x10d6f9710> can't render element of type <class 'sqlalchemy.dialects.postgresql.json.JSON'>
```

It worries me that it says `postgresql` while the readme tells me that it would use SQLite.

**Comment by jeena** [comment]
I see that special Postgres code is used in the models.py file for the settings and that it therefor it will not work with SQLite anymore.

**Comment by jeena** [comment]
I guess this should be reflected in the README and the default configuration.
